# Generated by Django 3.2 on 2022-06-19 14:29

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0025_auto_20220618_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='area_administrator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_tell',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
